export const ROHINGYA_UI = {
  home: 'Bari',
  back: 'Feri',
  chooseTopic: 'Bisoy bachho',
  hearDirections: 'Huno',
  stopAudio: 'Sowt bondho',
  tapHere: 'Eikhane dabao',
  startPractice: 'Amol shuru',
  listen: 'Huno',
  speak: 'Kou',
  repeat: 'Abar kou',
  start: 'Shuru',
  hearIt: 'Huno',
  repeatSlowly: 'Asta asta abar huno',
  tapToSpeak: 'Kou',
  tapToStop: 'Bondho',
  playing: 'Choli ase',
  nextPhrase: 'Ar akta',
  finish: 'Ses',
  exit: 'Bair o',
  practiceAgain: 'Abar amol',
  backHome: 'Bari zai',
  categoryPrompt: 'Fikra',
  of: 'moddhe',
  // Conversation screen
  connecting: 'Lagaise...',
  speakNow: 'Ekhon kou',
  aiSpeaking: 'Huno — se koisse',
  waitForTurn: 'Thaako — se koite ase',
  analyzing: 'Dekhaise...',
  conversationDone: 'Ses hoiye gese',
  categories: {
    healthcare: 'Daktar',
    school: 'Iskul',
    everyday: 'Rojor jibon',
    work: 'Kam',
    general: 'Sadharon kotha',
  },
} as const;
